In [8]:
import requests
import pandas as pd
import io
res = requests.get("https://www.twse.com.tw/rwd/zh/TAIEX/MI_5MINS_INDEX?date=20250905&response=csv&_=1757094098750", verify=False)
df = pd.read_csv(io.StringIO(res.text.replace("=", "")), header=1)
df = df.dropna(how='all', axis=1).dropna(how='all', axis=0)
df.head()

C:\Users\neoli\PycharmProjects\finlab\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.twse.com.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,時間,發行量加權股價指數,未含金融保險股指數,未含電子股指數,未含金融電子股指數,水泥類指數,食品類指數,塑膠類指數,紡織纖維類指數,電機機械類指數,...,航運類指數,觀光餐旅類指數,金融保險類指數,貿易百貨類指數,油電燃氣類指數,綠能環保類指數,數位雲端類指數,運動休閒類指數,居家生活類指數,其他類指數
0,09:00:00,"24,179.85","21,164.58","18,896.38","13,758.75",121.09,"2,067.95",117.84,510.73,395.10,...,188.75,112.23,"2,172.39",255.00,58.63,101.24,50.02,74.06,119.85,296.00
1,09:00:05,"24,244.26","21,226.07","18,918.74","13,780.12",121.12,"2,068.47",118.33,511.16,395.76,...,188.96,112.31,"2,173.62",255.31,58.63,101.24,50.02,74.16,119.85,296.04
2,09:00:10,"24,390.54","21,367.22","18,938.33","13,797.33",121.12,"2,068.47",118.44,511.81,397.07,...,188.97,112.42,"2,175.10",255.28,58.63,101.40,50.02,74.23,119.85,296.26
3,09:00:15,"24,424.84","21,398.71","18,959.76","13,815.55",121.12,"2,067.84",118.34,511.80,398.10,...,189.38,112.42,"2,176.88",255.29,58.87,101.51,49.99,74.31,119.83,297.08
4,09:00:20,"24,450.37","21,423.24","18,981.74","13,839.87",121.56,"2,071.10",118.00,512.41,399.64,...,189.94,112.51,"2,177.22",256.07,58.83,101.75,49.99,74.36,120.35,297.67